### ISSUE TITLE
[Keycloak Admin.create_user() ] Return Type Hint is incorrect

### ISSUE THREAD

**Issue by fabinca** [marcospereirampj/python-keycloak#544] opened 2024-04-08 13:09 UTC
![Screenshot from 2024-04-08 15-07-32](https://github.com/marcospereirampj/python-keycloak/assets/73344238/b40a7cde-89fd-4ac2-b842-d6bd5db1662a)
![Screenshot from 2024-04-08 15-08-07](https://github.com/marcospereirampj/python-keycloak/assets/73344238/c3f92732-f944-459c-a793-5ba8ee16e2f2)

```
user_id = keycloak_admin.create_user(
        {
            "username": username,
            "enabled": True,
            "emailVerified": True,
            "credentials": [{"value": password, "type": "password"}],
        },
        exist_ok=True,
    )
```

Above function returns the user_id, however type hints suggest it returns a dict, documentation suggests it returns a user representation.

**Comment by ryshoooo** [comment] 2024-04-08 13:11
Thanks for the report, I believe this is a duplicate of https://github.com/marcospereirampj/python-keycloak/issues/421

**Comment by fabinca** [comment] 2024-04-08 13:18
true I'm working on the pr

**Closed as completed** 2024-04-08 13:23 UTC
